input_dir = ""
output_dir = ""
template = "html"
filters = ["filters/set_title.lua", "filters/set_description.lua", "filters/format_date.lua", "filters/link_feed.lua", "filters/add_link_ext.lua]
pandoc_args = ["--standalone", --to=html"]

[feedmason]
domain = ""
author = ""
root = ""
feeds = []

[tagmason]
root = ""